#ifndef XBOXINTERNALS_GLOBAL_H
#define XBOXINTERNALS_GLOBAL_H

#if defined(XBOXINTERNALS_LIBRARY)
#  define XBOXINTERNALSSHARED_EXPORT
#else
#  define XBOXINTERNALSSHARED_EXPORT
#endif

#endif // XBOXINTERNALS_GLOBAL_H
